### PR TITLE
Add position in placeholders inside gettextf

### PR DESCRIPTION
**Pull request by shun2wang**
Part of https://github.com/jasp-stats/INTERNAL-jasp/issues/2125

### CODE REVIEW

**Comment by boutinb** [comment]
Unfortunately the previous commit has changed quite a lot the structure of the R files, and your PR has now Conflicting files:

- "%s subjects and %s raters/measurements. ICC type as referenced by Shrout & Fleiss (1979)." is now in intraclassCorrelatio0n.R
- "%s Of the observations, %1.f complete cases were used." is now in unidimensionalReliabilityBayesian/Frequentist.R files
- "%s Variables %s and %s correlated perfectly." is now in unidimensionalReliabilityFrequentist.R

**Comment by shun2wang** [comment]
Oops, This is because this PR has been here for a few days, and the experience has been incorporated in the middle. OK I will fix it.

@boutinb I had assigned you as reviewer for such PRs, please review and merge other PRs as soon as possible and start github action, thanks.

**Comment by boutinb** [comment]
@shun2wang Sorry I could not review before, but I was on holidays. You don't have to make a new PR, you can reuse this one.

**Comment by shun2wang** [comment]
ok, have a nice holiday! 😀

In order not to affect the merge of subsequent PRs, I will ask @Kucharssim  to review it.

**Comment by boutinb** [comment]
> In order not to affect the merge of subsequent PRs, I will ask @Kucharssim to review it.
I am back now. You can set me as reviewer also.

**Pull request closed without merging**
